---
tenants:
  - name: DC1
    vrfs:
      - name: default
        svis:
          - id: 110
            name: 'DC1_IDF1_DATA'
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.10.1
            nodes:
              - node: SPINE1
                ip_address: 10.1.10.2/24
              - node: SPINE2
                ip_address: 10.1.10.3/24
          - id: 120
            name: 'DC1_IDF1_VOICE'
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.20.1
            nodes:
              - node: SPINE1
                ip_address: 10.1.20.2/24
              - node: SPINE2
                ip_address: 10.1.20.3/24
          - id: 210
            name: 'DC1_IDF2_DAT'
            enabled: true
            ip_virtual_router_addresses:
              - 10.2.10.1
            nodes:
              - node: SPINE1
                ip_address: 10.2.10.2/24
              - node: SPINE2
                ip_address: 10.2.10.3/24