---
type: l2leaf

l2leaf:
  defaults:
    platform: vEOS
    mlag_peer_ipv4_pool: 10.253.1.0/31
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [ SPINE1, SPINE2 ]
    uplink_interfaces: [ Ethernet49, Ethernet50 ]
    mlag_interfaces: [ Ethernet51, Ethernet52 ]
  node_groups:
    - group: DC1-LEAF1
      nodes:
        - name: LEAF1A
          id: 1
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: LEAF1B
          id: 2
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: DC1-LEAF2
      nodes:
        - name: LEAF2A
          id: 3
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: LEAF2B
          id: 4
          mgmt_ip: 192.168.0.16/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]