---
type: l3spine

cv_tags_topology_type: spine

l3spine:
  defaults:
    platform: "7280R3"
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.252.1.0/24
    mlag_peer_ipv4_pool: 10.253.1.0/31
    mlag_peer_l3_ipv4_pool: 10.253.1.2/31
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [ Ethernet97/1, Ethernet98/1 ]

  node_groups:
    - group: DC1-SPINES
      nodes:
        - name: SPINE1
          id: 1
          mgmt_ip: 192.168.0.11/24
        - name: SPINE2
          id: 2
          mgmt_ip: 192.168.0.12/24