---
- name: Build Digital Twin Fabric Switch Configuration
  hosts: "{{ target_fabric }}"
  gather_facts: false
  vars:
    output_dir_name: "digital_twin/intended"
    documentation_dir_name: "digital_twin/documentation"
    avd_digital_twin_mode: true
  
  tasks:
    - name: Generate Structured Variables per Device
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate Intended Config and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

- name: Build Production Fabric Switch Configuration
  hosts: "{{ target_fabric }}"
  gather_facts: false
  
  tasks:
    - name: Generate Structured Variables per Device
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate Intended Config and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
