- name: Configuration deployment
  hosts: "{{ target_fabric }}"
  connection: local
  gather_facts: false
  
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 10.18.144.6
        cv_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc1NDMxMzc3ODY0OTczMzU0OTEsImRzbiI6ImF2ZF9kZXBsb3kiLCJkc3QiOiJhY2NvdW50IiwiZXhwIjoxNzU2NTYwNTg0LCJpYXQiOjE3NTYzMDEzODgsIm9naSI6Mywib2duIjoiRGVmYXVsdCIsInNpZCI6IjE3NTQ3Yjg4NTU1MzI3N2I0NGMyMDM5MWJjZTk3NGZkMWQxODZjOWI4MGU4ZDZiNTQ3MDRjZGUwYTg4Y2M0MzctdTEwWlQwOVJfT2FnQVNEQTdRT3lfdmtmVko0T2xGUGdSVUNNTDc2XyJ9.bdrIxxWGrCAYzVQjEa4D45twz_teNxaeL9_Rz_rTWuhrcoHxKLmRBaOWYlgh41sISmI9r-4_BcadyODtLeoUijr4Mpt_YMFrExK6DDOLnlX2kkv4IpOoWY_XbRbxQ3Kdi7HRyrflsPLAMKtdIy-VTz42UZnr7DWGO-9TpdM8ndbDmg0wv6UnZYLIbP1oP5_RRl31LxVaVdZVfJeHD_NfWAKQLDRqkKGDw08P4Mt2f9sUrAW2FrvQ-AArlIwiGkDWcliVqMoPYzkZlV5co3iWj_Fpg5aT3iItt0wqF-zjDyszDax4dIgrG8ZcfQcEdZjPSManCgjweE2o9ypVTQocZYQBx79-O__tnlpInx7K63HK7MSZ7Hcb-mGMJDhaDJQzfBm3_YE-fH6psBtn5FnDe2tI5wIxtaoEtqBgKJJllL7DTzmYBpvEtfwNOO6zy0xEu5oNoU4fcLi4Qn7rWXpCblG8JCm7Ht0_0dCLg-qgPoPNTrpE5i6MHzf25kbMcUFQj3IwvXEcQX6Jws491kZLL0dtcuPL4HYZb0I38AknWe2dWuqypJ8NnzfgaS8qzz9fEQy2pZFcuxnzDhkDEGEn_WzS386xOLFid_upZAYezhLSuODZtXh1dvH59Pv7wbtf_A3Gbp7P7_uTXXzGOcynTRy9c4d7D0zxDVtOxrAxfuM"
        cv_run_change_control: true
        cv_verify_certs: false