---
name: Deploy Configs to Digital Twin

on:
  pull_request:
    types:
      - closed

jobs:
  deploy_configs:
    if: github.event.pull_request.merged == true
    name: Deploy Configs to Digital Twin
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/aristanetworks/avd/universal:python3.12-avd-v5.5.1"
      options: '--user=root' #required, only user allowed by github actions
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.12/site-packages"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy Configs to Digital Twin CV Instance
        run: |
          make deploy-dc1_dt

  post_validate:
    name: Repository Dispatch
    needs: [ deploy_configs ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
              github.rest.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: "post-validate"
              })