---

name: Deploy Configs to Production

on:
  release:
    types:
      - published

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pre_change_validation:
    name: Pre-Change Validation of Production Environment
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/aristanetworks/avd/universal:python3.12-avd-v5.5.1"
      options: '--user=root' #required, only user allowed by github actions
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.12/site-packages"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run ANTA Against Production Fabric - Pre Deploy
        run: |
          make validate-dc1

      - name: Save output
        run: |
            cat sites/dc1/anta/reports/anta_report.md >> $GITHUB_STEP_SUMMARY

  deploy_configs:
    name: Deploy Configs to Production
    needs: [pre_change_validation]
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/aristanetworks/avd/universal:python3.12-avd-v5.5.1"
      options: '--user=root' #required, only user allowed by github actions
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.12/site-packages"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy Configs to Production Fabric
        run: |
          make deploy-dc1

  post_change_validation:
    name: Post-Change Validation of Production Environment
    needs: [deploy_configs]
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/aristanetworks/avd/universal:python3.12-avd-v5.5.1"
      options: '--user=root' #required, only user allowed by github actions
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.12/site-packages"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run ANTA Against Production Fabric - Post Deploy
        run: |
          make validate-dc1

      - name: Save output
        run: |
            cat sites/dc1/anta/reports/anta_report.md >> $GITHUB_STEP_SUMMARY

  build_mkdocs_trigger:
    name: Repository Dispatch
    needs: [ post_change_validation ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
              github.rest.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: "mkdocs"
              })