---
name: Deploy Configs to Digital Twin

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pre_change_validation:
    if: github.event.pull_request.merged == true
    name: Pre-Change Validation of Digital Twin Environment
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/aristanetworks/avd/universal:python3.12-avd-v5.5.1"
      options: '--user=root' #required, only user allowed by github actions
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.12/site-packages"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run ANTA Against Digital Twin CV Instance - Pre Deploy
        run: |
          make validate-dc1_dt

      - name: Save output
        run: |
            cat sites/dc1/anta/reports/anta_report.md >> $GITHUB_STEP_SUMMARY

  deploy_configs:
    name: Deploy Configs to Digital Twin
    needs: [pre_change_validation]
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/aristanetworks/avd/universal:python3.12-avd-v5.5.1"
      options: '--user=root' #required, only user allowed by github actions
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.12/site-packages"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy Configs to Digital Twin CV Instance
        run: |
          make deploy-dc1_dt

  post_change_validation:
    name: Post-Change Validation of Digital Twin Environment
    needs: [deploy_configs]
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/aristanetworks/avd/universal:python3.12-avd-v5.5.1"
      options: '--user=root' #required, only user allowed by github actions
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.12/site-packages"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run ANTA Against Digital Twin CV Instance - Post Deploy
        run: |
          make validate-dc1_dt

      - name: Save output
        run: |
            cat sites/dc1/anta/reports/anta_report.md >> $GITHUB_STEP_SUMMARY
